name: Build tests

on:
  push:
    paths:
      - '*/gen/**'
      - '*/solution/**'
      - '*/problem.json'
      - '*/solutions.json'
      - '*/subtasks.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dos2unix
        run: |
          sudo apt-get install dos2unix

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install tps
        run: |
          git clone https://github.com/ioi-2017/tps.git
          cd tps && sudo ./install-tps.sh

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            Arithmetic:
              - 'Arithmetic/gen/**'
              - 'Arithmetic/solution/**'
              - 'Arithmetic/problem.json'
              - 'Arithmetic/solutions.json'
              - 'Arithmetic/subtasks.json'

      - name: Build Arithmetic
        if: steps.changes.outputs.Arithmetic == 'true'
        working-directory: Arithmetic
        run: |
          tps gen -s
          git add tests/*.in
          git add tests/*.out
          git add tests/gen_summary
          git add tests/mapping

      - name: Commit tests and push
        run: |
          git diff-index --quiet HEAD -- || git commit -m "Build tests"
          git push
