name: Build statement

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
          sudo dpkg -i pandoc-2.10.1-1-amd64.deb

      - name: Check environment
        run: |
          pandoc -v
          xetex -v
          fc-list | grep "Noto Sans Mono CJK TC"
          fc-list | grep "Noto Sans CJK TC"
